/* 짝 맞추기 카드(기억력 놀이): 곱셈·10 만들기·분수·시계·소수 — 24장(12짝) 인쇄 */
window.GAME = function (host, api) {
  function clock(h, m) { var s = '<svg viewBox="0 0 100 100" class="pr-clk"><circle cx="50" cy="50" r="44" class="pr-face"/>'; for (var i = 0; i < 12; i++) { var a = i * 30 * Math.PI / 180; s += '<line x1="' + (50 + 38 * Math.sin(a)) + '" y1="' + (50 - 38 * Math.cos(a)) + '" x2="' + (50 + 43 * Math.sin(a)) + '" y2="' + (50 - 43 * Math.cos(a)) + '" stroke="#000" stroke-width="' + (i % 3 ? 1.5 : 3) + '"/>' } var ha = ((h % 12) + m / 60) * 30 * Math.PI / 180, ma = m * 6 * Math.PI / 180; return s + '<line x1="50" y1="50" x2="' + (50 + 22 * Math.sin(ha)) + '" y2="' + (50 - 22 * Math.cos(ha)) + '" stroke="#000" stroke-width="5" stroke-linecap="round"/><line x1="50" y1="50" x2="' + (50 + 34 * Math.sin(ma)) + '" y2="' + (50 - 34 * Math.cos(ma)) + '" stroke="#000" stroke-width="3" stroke-linecap="round"/><circle cx="50" cy="50" r="3"/></svg>' }
  function bar(a, b) { var s = '<svg viewBox="0 0 120 40" class="pr-bar">'; for (var i = 0; i < b; i++) s += '<rect x="' + (2 + i * 116 / b) + '" y="4" width="' + 116 / b + '" height="32" fill="' + (i < a ? '#9fb7e8' : '#fff') + '" stroke="#000" stroke-width="1.5"/>'; return s + '</svg>' }
  var K = {
    mul: { nm: '곱셈구구 (식 ↔ 답)', mk: function () { var s = {}, o = []; while (o.length < 12) { var a = 2 + CP.rnd(8), b = 2 + CP.rnd(8); if (s[a * b]) continue; s[a * b] = 1; o.push([a + ' × ' + b, String(a * b)]) } return o } },
    ten: { nm: '10 만들기 (점 ↔ 수, 18장)', mk: function () { var o = []; for (var a = 1; a <= 9; a++) o.push(['<span class="pr-dots">' + new Array(a + 1).join('●') + '</span>', String(10 - a)]); return o }, note: '점 카드와 수 카드를 더해 10이 되면 짝이에요.' },
    frac: { nm: '분수 (그림 ↔ 분수)', mk: function () { var L = [[1, 2], [1, 3], [2, 3], [1, 4], [3, 4], [1, 5], [2, 5], [3, 5], [1, 6], [5, 6], [3, 8], [5, 8]]; return L.map(function (p) { return [bar(p[0], p[1]), p[0] + '/' + p[1]] }) } },
    clock: { nm: '시계 (바늘 ↔ 시각)', mk: function () { var s = {}, o = []; while (o.length < 12) { var h = 1 + CP.rnd(12), m = CP.rnd(12) * 5; if (s[h + ':' + m]) continue; s[h + ':' + m] = 1; o.push([clock(h, m), h + '시 ' + (m ? m + '분' : '정각')]) } return o } },
    dec: { nm: '소수와 분수 (0.5 ↔ 1/2)', mk: function () { return [['0.1', '1/10'], ['0.2', '2/10'], ['0.3', '3/10'], ['0.5', '1/2'], ['0.25', '1/4'], ['0.75', '3/4'], ['0.7', '7/10'], ['0.9', '9/10'], ['0.4', '4/10'], ['0.6', '6/10'], ['0.8', '8/10'], ['1.5', '1과 1/2']] } }
  };
  host.innerHTML = '<div class="cp-set"><label>카드 종류 <select class="pr-k">' + Object.keys(K).map(function (k) { return '<option value="' + k + '">' + K[k].nm + '</option>' }).join('') + '</select></label><label>모둠 수 <input class="pr-g" type="number" min="1" max="10" value="1"></label><button type="button" class="tl-btn tl-go" data-a="print">🖨️ 카드 인쇄(모둠마다 한 벌)</button></div><div class="cp-prev"></div>';
  function sheet() { var k = host.querySelector('.pr-k').value, P = K[k].mk(), cards = []; P.forEach(function (p, i) { cards.push('<div class="pr-card pr-a">' + (/[<]/.test(p[0]) ? p[0] : CP.frac(p[0])) + '</div>', '<div class="pr-card pr-b">' + (/[<]/.test(p[1]) ? p[1] : CP.frac(p[1])) + '</div>') }); return '<div class="pr-cards">' + cards.join('') + '</div><p class="pr-rule"><b>규칙</b> (2~4명) 카드를 잘라 뒤집어 놓아요. 차례대로 두 장을 뒤집어 짝이면 가져가고 한 번 더, 아니면 다시 덮어요. 짝을 많이 모은 사람이 이겨요. ' + (K[k].note || '') + '</p>' }
  function prev() { host.querySelector('.cp-prev').innerHTML = CP.page(sheet(), '짝 맞추기 카드 · ' + K[host.querySelector('.pr-k').value].nm, false) }
  host.querySelector('.pr-k').onchange = prev;
  host.addEventListener('click', function (e) { var b = e.target.closest('button'); if (!b || b.dataset.a !== 'print') return; var g = Math.max(1, Math.min(10, +host.querySelector('.pr-g').value || 1)), h = ''; for (var i = 0; i < g; i++) h += CP.page(sheet(), '짝 맞추기 카드 · ' + K[host.querySelector('.pr-k').value].nm + (g > 1 ? ' (' + (i + 1) + '모둠)' : ''), false); CP.print(h) });
  prev(); api.bar('짝 맞추기 카드');
};
